//{namespace name=backend/static/order_status}
//{block name="backend/base/model/order_status" append}
Ext.define("Shopware.apps.Base.model.OrderStatus", {
	extend: "Shopware.apps.Base.model.OrderStatus",
    snippets: {
"cancelled": "{s name=cancelled}{/s}",
"open": "{s name=open}{/s}",
"in_process": "{s name=in_process}{/s}",
"completed": "{s name=completed}{/s}",
"partially_completed": "{s name=partially_completed}{/s}",
"cancelled_rejected": "{s name=cancelled_rejected}{/s}",
"ready_for_delivery": "{s name=ready_for_delivery}{/s}",
"partially_delivered": "{s name=partially_delivered}{/s}",
"completely_delivered": "{s name=completely_delivered}{/s}",
"clarification_required": "{s name=clarification_required}{/s}",
"Repair order": "{s name=Repair order}{/s}",
"review_necessary": "{s name=review_necessary}{/s}",
"PayPal oder sofortÜberweisung ausstehend": "{s name=PayPal oder sofortÜberweisung ausstehend}{/s}",
"Versandt (charry)": "{s name=Versandt (charry)}{/s}",
"charry-abgeholt-no-ni-versandt": "{s name=charry-abgeholt-no-ni-versandt}{/s}",
"Pay then we will ship": "{s name=Pay then we will ship}{/s}",
"Wartend": "{s name=Wartend}{/s}",
"AC-Artikel zurückerhalten": "{s name=AC-Artikel zurückerhalten}{/s}",
"in Leihphase": "{s name=in Leihphase}{/s}",
"wird zurück gesandt": "{s name=wird zurück gesandt}{/s}",
"Fehlgeschlagen": "{s name=Fehlgeschlagen}{/s}",
"Ratenzahlung zahlt nicht weiter": "{s name=Ratenzahlung zahlt nicht weiter}{/s}",
"Rückerstattet": "{s name=Rückerstattet}{/s}",
"Bar bezahlt": "{s name=Bar bezahlt}{/s}",
"Fertiggestellt": "{s name=Fertiggestellt}{/s}",
"1. Zahlungserinnerung": "{s name=1. Zahlungserinnerung}{/s}",
"2. Zahlungserinnerung": "{s name=2. Zahlungserinnerung}{/s}",
"Yasine versenden": "{s name=Yasine versenden}{/s}",
"Versandt (AC)": "{s name=Versandt (AC)}{/s}",
"AC-Yasin solls bearbeiten": "{s name=AC-Yasin solls bearbeiten}{/s}",
"Bitte Versenden (AC)": "{s name=Bitte Versenden (AC)}{/s}",
"Ausfuhrdokument wird nachgereicht": "{s name=Ausfuhrdokument wird nachgereicht}{/s}",
"AC artikel fehlt": "{s name=AC artikel fehlt}{/s}",
"Storniert": "{s name=Storniert}{/s}",
"kam zurück (charry)": "{s name=kam zurück (charry)}{/s}",
"Wird abgeholt oder installiert": "{s name=Wird abgeholt oder installiert}{/s}",
"Bitte Versenden (GUS)": "{s name=Bitte Versenden (GUS)}{/s}",
"Versandt (Lieferant)": "{s name=Versandt (Lieferant)}{/s}",
"Zahlung eingegangen": "{s name=Zahlung eingegangen}{/s}",
"Ratenzahlung": "{s name=Ratenzahlung}{/s}",
"persönlich abgeholt": "{s name=persönlich abgeholt}{/s}",
"Yasin soll beenden": "{s name=Yasin soll beenden}{/s}",
"Bitte Versenden (Lieferant)": "{s name=Bitte Versenden (Lieferant)}{/s}",
"Installiert": "{s name=Installiert}{/s}",
"AC-verpackt (charry)": "{s name=AC-verpackt (charry)}{/s}",
"Versandt (GUS)": "{s name=Versandt (GUS)}{/s}",
"Versand erst bei Zahlungseingang": "{s name=Versand erst bei Zahlungseingang}{/s}",
"Reparatur Auftrag": "{s name=Reparatur Auftrag}{/s}",
"Bestellung überprüft - in Bearbeitung": "{s name=Bestellung überprüft - in Bearbeitung}{/s}",
"Artikel erwartet": "{s name=Artikel erwartet}{/s}",
"AC unzustellbar zurück": "{s name=AC unzustellbar zurück}{/s}",

    },
});
//{/block}